import z from 'zod';

const envSchema = z.object({
  NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string(),
  NEXT_PUBLIC_APPNAME: z.string(),
  NEXT_PUBLIC_CHROME_EXTENSIONS: z.string(),
  NEXT_PUBLIC_X_LINK: z.string(),
  NEXT_PUBLIC_X_USERNAME: z.string(),
  NEXT_PUBLIC_GITHUB_LINK: z.string(),
  NEXT_PUBLIC_GA_MEASUREMENT_ID: z.string(),
  NEXT_PUBLIC_MS_CLARITY_CODE: z.string(),
});

const envClientSchema = envSchema.parse({
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_APPNAME: process.env.NEXT_PUBLIC_APPNAME,
  NEXT_PUBLIC_CHROME_EXTENSIONS: process.env.NEXT_PUBLIC_CHROME_EXTENSIONS,
  NEXT_PUBLIC_X_LINK: process.env.NEXT_PUBLIC_X_LINK,
  NEXT_PUBLIC_X_USERNAME: process.env.NEXT_PUBLIC_X_USERNAME,
  NEXT_PUBLIC_GITHUB_LINK: process.env.NEXT_PUBLIC_GITHUB_LINK,
  NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
  NEXT_PUBLIC_MS_CLARITY_CODE: process.env.NEXT_PUBLIC_MS_CLARITY_CODE,
});

export default envClientSchema;
